# Model Analysis

## Library setup

Disable some console warnings

In [1]:
import os
os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

Import libraries

In [2]:
import h5py
import numpy as np
import pandas as pd

## Load models

### QKeras model (HDF5)

<p style="background-color:Tomato;"><b>DO NOT USE HDF5 FOR THIS ANALYSIS. MODELS WITH BATCHNORM FOLDING GET SAVED WITHOUT AN EXPLICIT FOLDING SO RESULTS MAY BE MISLEADING!</b></p>

In [3]:
MODEL_DIR = 'models'

In [4]:
# hf_qmodel_l0 = h5py.File(MODEL_DIR + '/ds8l0_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l0 = h5py.File(MODEL_DIR + '/ds8l0_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l1 = h5py.File(MODEL_DIR + '/ds8l1_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l1 = h5py.File(MODEL_DIR + '/ds8l1_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l2 = h5py.File(MODEL_DIR + '/ds8l2_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l2 = h5py.File(MODEL_DIR + '/ds8l2_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l3 = h5py.File(MODEL_DIR + '/ds8l3_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l3 = h5py.File(MODEL_DIR + '/ds8l3_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l4 = h5py.File(MODEL_DIR + '/ds8l4_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l4 = h5py.File(MODEL_DIR + '/ds8l4_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l5 = h5py.File(MODEL_DIR + '/ds8l5_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l5 = h5py.File(MODEL_DIR + '/ds8l5_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l6 = h5py.File(MODEL_DIR + '/ds8l6_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l6 = h5py.File(MODEL_DIR + '/ds8l6_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l7 = h5py.File(MODEL_DIR + '/ds8l7_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l7 = h5py.File(MODEL_DIR + '/ds8l7_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l8 = h5py.File(MODEL_DIR + '/ds8l8_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l8 = h5py.File(MODEL_DIR + '/ds8l8_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l9 = h5py.File(MODEL_DIR + '/ds8l9_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l9 = h5py.File(MODEL_DIR + '/ds8l9_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l10 = h5py.File(MODEL_DIR + '/ds8l10_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l10 = h5py.File(MODEL_DIR + '/ds8l10_noscaling_qkeras_d64_model.h5', 'r')
# hf_qmodel_l11 = h5py.File(MODEL_DIR + '/ds8l11_noscaling_qkeras_d64_model_q_weights.h5', 'r')
# hf_model_l11 = h5py.File(MODEL_DIR + '/ds8l11_noscaling_qkeras_d64_model.h5', 'r')

hf_model_l0  = h5py.File(MODEL_DIR +  '/ds8l0_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l1  = h5py.File(MODEL_DIR +  '/ds8l1_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l2  = h5py.File(MODEL_DIR +  '/ds8l2_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l3  = h5py.File(MODEL_DIR +  '/ds8l3_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l4  = h5py.File(MODEL_DIR +  '/ds8l4_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l5  = h5py.File(MODEL_DIR +  '/ds8l5_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l6  = h5py.File(MODEL_DIR +  '/ds8l6_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l7  = h5py.File(MODEL_DIR +  '/ds8l7_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l8  = h5py.File(MODEL_DIR +  '/ds8l8_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l9  = h5py.File(MODEL_DIR +  '/ds8l9_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l10 = h5py.File(MODEL_DIR + '/ds8l10_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')
hf_model_l11 = h5py.File(MODEL_DIR + '/ds8l11_noscaling_qkeras_foldbatchnorm_d64_model.h5', 'r')

#### Visualize QKeras model (HDF5)

### hls4ml model (.csv)

Collect data from the .csv files (essentially the .txt files of an hls4ml projects).

In [5]:
with h5py.File('weights.hdf5', 'w') as hf:
    for i in range(12):
        # df_dense1_w = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_d64_vivado_prj/firmware/weights/w2.txt', header=None)
        # df_dense1_b = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_d64_vivado_prj/firmware/weights/b2.txt', header=None)
        # df_dense2_w = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_d64_vivado_prj/firmware/weights/w6.txt', header=None)
        # df_dense2_b = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_d64_vivado_prj/firmware/weights/b6.txt', header=None)
        
        df_dense1_w = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_foldbatchnorm_d64_vivado_prj/firmware/weights/w2.txt', header=None)
        df_dense1_b = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_foldbatchnorm_d64_vivado_prj/firmware/weights/b2.txt', header=None)
        df_dense2_w = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_foldbatchnorm_d64_vivado_prj/firmware/weights/w5.txt', header=None)
        df_dense2_b = pd.read_csv('hls4ml_ds8l' + str(i) + '_noscaling_qkeras_foldbatchnorm_d64_vivado_prj/firmware/weights/b5.txt', header=None)

        dset = hf.create_dataset('/l' + str(i) + '/dense1/w', data=df_dense1_w.values[0])
        dset = hf.create_dataset('/l' + str(i) + '/dense1/b', data=df_dense1_b.values[0])
        dset = hf.create_dataset('/l' + str(i) + '/dense2/w', data=df_dense2_w.values[0])
        dset = hf.create_dataset('/l' + str(i) + '/dense2/b', data=df_dense2_b.values[0])

#### Visualize hls4ml model (.csv)

In [6]:
with h5py.File('weights.hdf5', 'r') as hf:
    print(hf.keys())

<KeysViewHDF5 ['l0', 'l1', 'l10', 'l11', 'l2', 'l3', 'l4', 'l5', 'l6', 'l7', 'l8', 'l9']>


In [7]:
with h5py.File('weights.hdf5', 'r') as hf:
    print(hf['/l0/dense1/w'])
    print(hf['/l0/dense1/b'])
    print(hf['/l0/dense2/w'])
    print(hf['/l0/dense2/b'])

<HDF5 dataset "w": shape (832,), type "<f8">
<HDF5 dataset "b": shape (64,), type "<f8">
<HDF5 dataset "w": shape (192,), type "<f8">
<HDF5 dataset "b": shape (3,), type "<f8">


In [8]:
with h5py.File('weights.hdf5', 'r') as hf:
    print('Model l0 dense1 w[0][0]', hf['/l0/dense1/w'][0])
    print('Model l0 dense1 w[0][1]', hf['/l0/dense1/w'][1])
    print('Model l0 dense1 w[0][2]', hf['/l0/dense1/w'][2])
    print('Model l0 dense1 w[0][3]', hf['/l0/dense1/w'][3])
    print('Model l0 dense1 w[0][4]', hf['/l0/dense1/w'][4])
    print('Model l0 dense1 w[0][5]', hf['/l0/dense1/w'][5])
    print('...')
    print('Model l0 dense1 w[11][63]', hf['/l0/dense1/w'][63])

Model l0 dense1 w[0][0] -0.6875
Model l0 dense1 w[0][1] -0.3125
Model l0 dense1 w[0][2] -0.3125
Model l0 dense1 w[0][3] 0.3125
Model l0 dense1 w[0][4] 0.0
Model l0 dense1 w[0][5] 0.0
...
Model l0 dense1 w[11][63] 0.125


### Compare QKeras (HDF5) and hls4ml (.csv) data

<p style="background-color:Tomato;"><b>DO NOT COMPARE HDF5 AND CSV DATA. IF THE MODEL HAS BATCHNORM FOLDING THEN IT WILL NOT MATCH.</b></p>

## Check weights

In [14]:
with h5py.File('weights.hdf5', 'r') as hf:
    df_dense1_w_size = hf['/l0/dense1/w'].shape[0]
    df_dense1_b_size = hf['/l0/dense1/b'].shape[0]
    df_dense2_w_size = hf['/l0/dense2/w'].shape[0]
    df_dense2_b_size = hf['/l0/dense2/b'].shape[0]

    N_MODELS = 12

    print('Across', N_MODELS, 'models:')

    ##
    ## Dense 1
    ##
    total = 0 # count of weight columns that are the same
    for i in range(df_dense1_w_size): # for each weight column
        c = 0
        for j in range(N_MODELS):  # for each model
            if (hf['/l' + str(j) + '/dense1/w'][i] == hf['/l0/dense1/w'][i]):
                c = c + 1
        if (c == N_MODELS):
            total = total + 1
    print('- Dense1.w: count of weight columns that are the same', total)

    total = 0 # count of weight columns that are the same
    for i in range(df_dense1_b_size): # for each weight column
        c = 0
        for j in range(N_MODELS):  # for each model
            if (hf['/l' + str(j) + '/dense1/b'][i] == hf['/l0/dense1/b'][i]):
                c = c + 1
        if (c == N_MODELS):
            total = total + 1
    print('- Dense1.b: count of weight columns that are the same', total)

    ##
    ## Dense 2
    ##
    total = 0 # count of weight columns that are the same
    for i in range(df_dense2_w_size): # for each weight column
        c = 0
        for j in range(N_MODELS):  # for each model
            if (hf['/l' + str(j) + '/dense2/w'][i] == hf['/l0/dense2/w'][i]):
                c = c + 1
        if (c == N_MODELS):
            total = total + 1
    print('- Dense2.w: count of weight columns that are the same', total)

    total = 0 # count of weight columns that are the same
    for i in range(df_dense2_b_size): # for each weight column
        c = 0
        for j in range(N_MODELS):  # for each model
            if (hf['/l' + str(j) + '/dense2/b'][i] == hf['/l0/dense2/b'][i]):
                c = c + 1
        if (c == N_MODELS):
            total = total + 1
    print('- Dense2.b: count of weight columns that are the same', total)

Across 12 models:
- Dense1.w: count of weight columns that are the same 0
- Dense1.b: count of weight columns that are the same 0
- Dense2.w: count of weight columns that are the same 0
- Dense2.b: count of weight columns that are the same 0


In [21]:
with h5py.File('weights.hdf5', 'r') as hf:
    print(hf['/l0/dense1/w'][:8])
    print(hf['/l1/dense1/w'][:8])
    print(hf['/l2/dense1/w'][:8])
    print(hf['/l3/dense1/w'][:8])
    print(hf['/l4/dense1/w'][:8])
    print(hf['/l5/dense1/w'][:8])
    print(hf['/l6/dense1/w'][:8])
    print(hf['/l7/dense1/w'][:8])
    print(hf['/l8/dense1/w'][:8])
    print(hf['/l9/dense1/w'][:8])
    print(hf['/l10/dense1/w'][:8])
    print(hf['/l11/dense1/w'][:8])

[-0.6875 -0.3125 -0.3125  0.3125  0.      0.     -0.1875  0.0625]
[-0.25    0.0625 -0.1875  0.125   0.4375  0.125   0.25    0.    ]
[ 0.     -0.125   0.     -0.0625  0.     -0.125   0.4375  0.5   ]
[ 0.     -0.0625  0.      0.      0.0625 -0.125   0.25    0.125 ]
[ 0.0625  0.0625  0.      0.125   0.125   0.     -0.0625  0.3125]
[ 0.0625  0.     -0.0625 -0.125   0.     -0.0625  0.0625 -0.0625]
[ 0.125   0.      0.125   0.     -0.0625 -0.125   0.0625  0.0625]
[ 0.25   -0.0625  0.      0.     -0.125   0.0625 -0.375   0.0625]
[ 0.0625  0.      0.125   0.125   0.0625  0.0625 -0.125  -0.0625]
[0.     0.0625 0.0625 0.     0.125  0.     0.     0.    ]
[ 0.     -0.0625  0.      0.      0.0625 -0.125  -0.0625  0.    ]
[0.     0.0625 0.     0.0625 0.0625 0.0625 0.0625 0.1875]
