In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import read_csv
import math
import seaborn as sns

In [2]:
#df1 is the trueTestPT - this is the true PT (it's a floating point number) from the dataset
df1 = pd.read_csv('/home/jieun201/aug20_make3Classes_dataset/trainTestSamples/test/trueTestPT.csv')
#df2 is the PT label (e.g., for multiclassifier 0,1,2) that is predicted 
df2 = pd.read_csv('predictionsFiles.csv')
#df3 is the PT label (e.g., for multiclassifier 0,1,2) that is true 
df3 = pd.read_csv('aug22true.csv')
df2.columns.values[0] = "predict"
df3.columns.values[0] = "true"
df2['predict'] = df2['predict'].astype(int)

In [3]:
concatenate = pd.concat([df1,df2, df3], axis=1)

In [4]:
list1 = [] #this holds the number of entries in each bin
list2 = [] #this holds the value, here counts how many entries are predicted as "0"

In [5]:
binValidate1 = concatenate.loc[(concatenate['pt'] > -0.1) & (concatenate['pt'] <= 0.0)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate1.predict == 0))/(binValidate1.shape[0]) )

binValidate2 = concatenate.loc[(concatenate['pt'] > -0.2) & (concatenate['pt'] <= -0.1)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate2.predict == 0))/(binValidate2.shape[0]) )

binValidate3 = concatenate.loc[(concatenate['pt'] >-0.3) & (concatenate['pt'] <= -0.2)]
list1.append( binValidate3.shape[0])
list2.append( sum((binValidate3.predict == 0))/(binValidate3.shape[0]) )

In [6]:
bin4 = concatenate.loc[  ((concatenate['pt'] > -0.4) & (concatenate['pt'] <= -0.3)  )       ]
list1.append(bin4.shape[0])
list2.append( sum((bin4.predict == 0))/(bin4.shape[0]))

In [7]:
bin5 = concatenate.loc[  ((concatenate['pt'] > -0.5) & (concatenate['pt'] <= -0.4)  )] 
list1.append(bin5.shape[0])
list2.append( sum((bin5.predict == 0))/(bin5.shape[0]))

In [8]:
bin6 = concatenate.loc[ ( (concatenate['pt'] > -0.6) & (concatenate['pt'] <= -0.5)   )]
#bin6 = concatenate.loc[(concatenate['pt'] < 0.6) & (concatenate['pt'] >= 0.5)]
list1.append(bin6.shape[0])
list2.append( sum((bin6.predict == 0))/(bin6.shape[0]) )

In [9]:
bin7 = concatenate.loc[  ( (concatenate['pt'] > -0.7) & (concatenate['pt'] <= -0.6)   )] 
#bin7 = concatenate.loc[(concatenate['pt'] < 0.7) & (concatenate['pt'] >= 0.6)]
list1.append(bin7.shape[0])
list2.append( sum((bin7.predict == 0))/(bin7.shape[0]) )

In [10]:
bin8 = concatenate.loc[  ( (concatenate['pt'] > -0.8) & (concatenate['pt'] <= -0.7)    )]
#bin8 = concatenate.loc[(concatenate['pt'] < 0.8) & (concatenate['pt'] >= 0.7)]
list1.append(bin8.shape[0])
list2.append( sum((bin8.predict == 0))/(bin8.shape[0]) )

In [11]:
bin9 = concatenate.loc[  ( (concatenate['pt'] > -0.9) & (concatenate['pt'] <= -0.8)   )] 
#bin9 = concatenate.loc[(concatenate['pt'] < 0.9) & (concatenate['pt'] >= 0.8)]
list1.append(bin9.shape[0])
list2.append( sum((bin9.predict == 0))/(bin9.shape[0]) )

In [12]:
bin10 = concatenate.loc[  ( (concatenate['pt'] > -1.0) & (concatenate['pt'] <= -0.9)    )]
#bin10 = concatenate.loc[(concatenate['pt'] < 1.0) & (concatenate['pt'] >= 0.9)]
list1.append(bin10.shape[0])
list2.append( sum((bin10.predict == 0))/(bin10.shape[0]) )

In [13]:
bin11 = concatenate.loc[  ( (concatenate['pt'] > -1.1) & (concatenate['pt'] <= -1.0)    )]
#bin11 = concatenate.loc[(concatenate['pt'] < 1.1) & (concatenate['pt'] >= 1.0)]
list1.append(bin11.shape[0])
list2.append( sum((bin11.predict == 0))/(bin11.shape[0]) )

In [14]:
bin12 = concatenate.loc[  ( (concatenate['pt'] > -1.2) & (concatenate['pt'] <= -1.1)    )]
#bin12 = concatenate.loc[(concatenate['pt'] < 1.2) & (concatenate['pt'] >= 1.1)]
list1.append(bin12.shape[0])
list2.append( sum((bin12.predict == 0))/(bin12.shape[0]) )

In [15]:
bin13 = concatenate.loc[  ( (concatenate['pt'] > -1.3) & (concatenate['pt'] <= -1.2)    )]
#bin13 = concatenate.loc[(concatenate['pt'] < 1.3) & (concatenate['pt'] >= 1.2)]
list1.append(bin13.shape[0])
list2.append( sum((bin13.predict == 0))/(bin13.shape[0]) )

In [16]:
bin14 = concatenate.loc[  ( (concatenate['pt'] > -1.4) & (concatenate['pt'] <= -1.3)    )]
#bin14 = concatenate.loc[(concatenate['pt'] < 1.4) & (concatenate['pt'] >= 1.3)]
list1.append(bin14.shape[0])
list2.append( sum((bin14.predict == 0))/(bin14.shape[0]) )

In [17]:
bin15 = concatenate.loc[ ( (concatenate['pt'] > -1.5) & (concatenate['pt'] <= -1.4)   )] 
#bin15 = concatenate.loc[(concatenate['pt'] < 1.5) & (concatenate['pt'] >= 1.4)]
list1.append(bin15.shape[0])
list2.append( sum((bin15.predict == 0))/(bin15.shape[0]) )

In [18]:
bin16 = concatenate.loc[  ( (concatenate['pt'] > -1.6) & (concatenate['pt'] <= -1.5)   )] 
#bin16 = concatenate.loc[(concatenate['pt'] < 1.6) & (concatenate['pt'] >= 1.5)]
list1.append(bin16.shape[0])
list2.append( sum((bin16.predict == 0))/(bin16.shape[0]) )

In [19]:
bin17 = concatenate.loc[  ( (concatenate['pt'] > -1.7) & (concatenate['pt'] <= -1.6)    )]
#bin17 = concatenate.loc[(concatenate['pt'] < 1.7) & (concatenate['pt'] >= 1.6)]
list1.append(bin17.shape[0])
list2.append( sum((bin17.predict == 0))/(bin17.shape[0]) )

In [20]:
bin18 = concatenate.loc[  ( (concatenate['pt'] > -1.8) & (concatenate['pt'] <= -1.7)    )]
#bin18 = concatenate.loc[(concatenate['pt'] < 1.8) & (concatenate['pt'] >= 1.7)]
list1.append(bin18.shape[0])
list2.append( sum((bin18.predict == 0))/(bin18.shape[0]) )

In [21]:
bin19 = concatenate.loc[ ( (concatenate['pt'] > -1.9) & (concatenate['pt'] <= -1.8)   )] 
#bin19 = concatenate.loc[(concatenate['pt'] < 1.9) & (concatenate['pt'] >= 1.8)]
list1.append(bin19.shape[0])
list2.append( sum((bin19.predict == 0))/(bin19.shape[0]) )

In [22]:
bin20 = concatenate.loc[ ( (concatenate['pt'] > -2.0) & (concatenate['pt'] <= -1.9)    )]
#bin20 = concatenate.loc[(concatenate['pt'] < 2.0) & (concatenate['pt'] >= 1.9)]
list1.append(bin20.shape[0])
list2.append( sum((bin20.predict == 0))/(bin20.shape[0]) )

In [23]:
bin21 = concatenate.loc[  ( (concatenate['pt'] > -2.1) & (concatenate['pt'] <= -2.0)    )]
#bin21 = concatenate.loc[(concatenate['pt'] < 2.1) & (concatenate['pt'] >= 2.0)]
list1.append(bin21.shape[0])
list2.append( sum((bin21.predict == 0))/(bin21.shape[0]) )

In [24]:
bin22 = concatenate.loc[  ( (concatenate['pt'] > -2.2) & (concatenate['pt'] <= -2.1)    )]
#bin22 = concatenate.loc[(concatenate['pt'] < 2.2) & (concatenate['pt'] >= 2.1)]
list1.append(bin22.shape[0])
list2.append( sum((bin22.predict == 0))/(bin22.shape[0]) )

In [25]:
bin23 = concatenate.loc[  ( (concatenate['pt'] > -2.3) & (concatenate['pt'] <= -2.2)    )]
#bin23 = concatenate.loc[(concatenate['pt'] < 2.3) & (concatenate['pt'] >= 2.2)]
list1.append(bin23.shape[0])
list2.append( sum((bin23.predict == 0))/(bin23.shape[0]) )

In [26]:
bin24 = concatenate.loc[ ( (concatenate['pt'] > -2.4) & (concatenate['pt'] <= -2.3)    )]
#bin24 = concatenate.loc[(concatenate['pt'] < 2.4) & (concatenate['pt'] >= 2.3)]
list1.append(bin24.shape[0])
list2.append( sum((bin24.predict == 0))/(bin24.shape[0]) )

In [27]:
bin25 = concatenate.loc[  ( (concatenate['pt'] > -2.5) & (concatenate['pt'] <= -2.4)    )]
#bin25 = concatenate.loc[(concatenate['pt'] < 2.5) & (concatenate['pt'] >= 2.4)]
list1.append(bin25.shape[0])
list2.append( sum((bin25.predict == 0))/(bin25.shape[0]) )

In [28]:
bin26 = concatenate.loc[  ( (concatenate['pt'] > -2.6) & (concatenate['pt'] <= -2.5)    )]
#bin26 = concatenate.loc[(concatenate['pt'] < 2.6) & (concatenate['pt'] >= 2.5)]
list1.append(bin26.shape[0])
list2.append( sum((bin26.predict == 0))/(bin26.shape[0]) )

In [29]:
bin27 = concatenate.loc[  ( (concatenate['pt'] > -2.7) & (concatenate['pt'] <= -2.6)    )]
#bin27 = concatenate.loc[(concatenate['pt'] < 2.7) & (concatenate['pt'] >= 2.6)]
list1.append(bin27.shape[0])
list2.append( sum((bin27.predict == 0))/(bin27.shape[0]) )

In [30]:
bin28 = concatenate.loc[  ( (concatenate['pt'] > -2.8) & (concatenate['pt'] <= -2.7)    )]
#bin28 = concatenate.loc[(concatenate['pt'] < 2.8) & (concatenate['pt'] >= 2.7)]
list1.append(bin28.shape[0])
list2.append( sum((bin28.predict == 0))/(bin28.shape[0]) )

In [31]:
bin29 = concatenate.loc[   ( (concatenate['pt'] > -2.9) & (concatenate['pt'] <= -2.8)    )]
#bin29 = concatenate.loc[(concatenate['pt'] < 2.9) & (concatenate['pt'] >= 2.8)]
list1.append(bin29.shape[0])
list2.append( sum((bin29.predict == 0))/(bin29.shape[0]) )

In [32]:
bin30 = concatenate.loc[  ( (concatenate['pt'] > -3.0) & (concatenate['pt'] <= -2.9)    )]
#bin30 = concatenate.loc[(concatenate['pt'] < 3.0) & (concatenate['pt'] >= 2.9)]
list1.append(bin30.shape[0])
list2.append( sum((bin30.predict == 0))/(bin30.shape[0]) )

In [33]:
bin31 = concatenate.loc[  ( (concatenate['pt'] > -3.1) & (concatenate['pt'] <= -3.0)    )]
bin32 = concatenate.loc[  ( (concatenate['pt'] > -3.2) & (concatenate['pt'] <= -3.1)    )]
bin33 = concatenate.loc[   ( (concatenate['pt'] > -3.3) & (concatenate['pt'] <= -3.2)    )]
bin34 = concatenate.loc[  ( (concatenate['pt'] > -3.4) & (concatenate['pt'] <= -3.3)    )]
bin35 = concatenate.loc[  ( (concatenate['pt'] > -3.5) & (concatenate['pt'] <= -3.4)    )]
bin31_35 = bin31.shape[0] + bin32.shape[0]+ bin33.shape[0] + bin34.shape[0]+ bin35.shape[0]
list1.append(bin31_35)
list2.append((sum(bin31.predict == 0) +sum(bin32.predict == 0) + sum(bin33.predict == 0) + sum(bin34.predict == 0) + sum(bin35.predict == 0))/bin31_35 ) 

In [34]:
bin36 = concatenate.loc[  ( (concatenate['pt'] > -3.6) & (concatenate['pt'] <= -3.5)    )]
bin37 = concatenate.loc[  ( (concatenate['pt'] > -3.7) & (concatenate['pt'] <= -3.6)    )]
bin38 = concatenate.loc[ ( (concatenate['pt'] > -3.8) & (concatenate['pt'] <= -3.7)    )]
bin39 = concatenate.loc[   ( (concatenate['pt'] > -3.9) & (concatenate['pt'] <= -3.8)    )]
bin40 = concatenate.loc[ ( (concatenate['pt'] > -4.0) & (concatenate['pt'] <= -3.9)    )]
bin36_40 = bin36.shape[0] + bin37.shape[0]+ bin38.shape[0] + bin39.shape[0]+ bin40.shape[0]
list1.append(bin36_40)
list2.append((sum(bin36.predict == 0) +sum(bin37.predict == 0) + sum(bin38.predict == 0) + sum(bin39.predict == 0) + sum(bin40.predict == 0))/bin36_40 ) 

In [35]:
bin41 = concatenate.loc[  ( (concatenate['pt'] > -4.1) & (concatenate['pt'] <= -4.0)    )]
bin42 = concatenate.loc[   ( (concatenate['pt'] > -4.2) & (concatenate['pt'] <= -4.1)    )]
bin43 = concatenate.loc[   ( (concatenate['pt'] > -4.3) & (concatenate['pt'] <= -4.2)    )]
bin44 = concatenate.loc[   ( (concatenate['pt'] > -4.4) & (concatenate['pt'] <= -4.3)  )]
bin45 = concatenate.loc[   ( (concatenate['pt'] > -4.5) & (concatenate['pt'] <= -4.4)    )]
bin41_45 = bin41.shape[0] + bin42.shape[0]+ bin43.shape[0] + bin44.shape[0]+ bin45.shape[0] 
list1.append(bin41_45)
list2.append((sum(bin41.predict == 0) +sum(bin42.predict == 0) + sum(bin43.predict == 0) + sum(bin44.predict == 0) + sum(bin45.predict == 0))/bin41_45 ) 

In [36]:
bin46 = concatenate.loc[   ( (concatenate['pt'] > -4.6) & (concatenate['pt'] <= -4.5)    )]
bin47 = concatenate.loc[  ( (concatenate['pt'] > -4.7) & (concatenate['pt'] <= -4.6)    )]
bin48 = concatenate.loc[   ( (concatenate['pt'] > -4.8) & (concatenate['pt'] <= -4.7)    )]
bin49 = concatenate.loc[   ( (concatenate['pt'] > -4.9) & (concatenate['pt'] <= -4.8)    )]
bin50 = concatenate.loc[ ( (concatenate['pt'] > -5.0) & (concatenate['pt'] <= -4.9)    )]
bin46_50 = bin46.shape[0] + bin47.shape[0]+ bin48.shape[0] + bin49.shape[0]+ bin50.shape[0]  
list1.append(bin46_50)
list2.append((sum(bin46.predict == 0) +sum(bin47.predict == 0) + sum(bin48.predict == 0) + sum(bin49.predict == 0) + sum(bin50.predict == 0))/bin46_50 ) 

In [37]:
reversed_list2 = list2[::-1]
#reversed_list2

In [38]:
len(reversed_list2)

34

In [39]:
xvalues = [-0.1,-0.2,-0.3,-0.4,-0.5,-0.6,-0.7,-0.8,-0.9,-1.0,-1.1,-1.2,-1.3,-1.4,-1.5,-1.6,-1.7,-1.8,-1.9,-2.0,-2.1,-2.2,-2.3,-2.4,-2.5,-2.6,-2.7,-2.8,-2.9,-3.0,-3.5,-4.0,-4.5,-4.9]

In [40]:
len(xvalues)

34

In [41]:
reversed_list = list1[::-1]

In [42]:
y_values=np.array([reversed_list2])
y_values

array([[0.81538462, 0.83928571, 0.93069307, 0.8974359 , 0.88034188,
        0.86363636, 0.88957055, 0.90721649, 0.91866029, 0.91353383,
        0.93602694, 0.88685015, 0.87700535, 0.8907563 , 0.89208633,
        0.90202177, 0.90594059, 0.88925439, 0.89478114, 0.88992806,
        0.89582107, 0.88801572, 0.88932651, 0.87637185, 0.8757515 ,
        0.86485071, 0.84401817, 0.8379641 , 0.79846743, 0.75663495,
        0.68045977, 0.48398385, 0.24499788, 0.1       ]])

In [43]:
x_values=np.array([reversed_list])
x_values

array([[  65,  112,  202,  390,  117,  110,  163,  194,  209,  266,  297,
         327,  374,  476,  556,  643,  808,  912, 1188, 1390, 1699, 2036,
        2539, 3098, 3992, 3818, 3962, 4067, 3915, 3994, 3915, 3715,  120,
         120]])

In [44]:
first = y_values*(1-y_values)
second = first/x_values
errors = np.sqrt(second)
errors

array([[0.04812365, 0.03470349, 0.01786964, 0.01536268, 0.03000571,
        0.03272038, 0.02454928, 0.02083003, 0.01890844, 0.01723235,
        0.01419922, 0.01751775, 0.01698277, 0.01429796, 0.01315844,
        0.01172378, 0.01026941, 0.01039151, 0.00890219, 0.00839476,
        0.00741146, 0.00698876, 0.00622617, 0.00591374, 0.00522084,
        0.00553299, 0.00576442, 0.00577805, 0.00641114, 0.00678998,
        0.00745243, 0.00819913, 0.0392613 , 0.02738613]])

In [45]:
np.savetxt('NegativeYValues.out',y_values, delimiter=',')
np.savetxt('errorsNegative.out', errors, delimiter=',')