In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import read_csv
import math
import seaborn as sns

In [2]:
df1 = pd.read_csv('/home/jieun201/aug20_make3Classes_dataset/trainTestSamples/test/trueTestPT.csv')
df2 = pd.read_csv('predictionsFiles.csv')
df3 = pd.read_csv('aug22true.csv')
df2.columns.values[0] = "predict"
df3.columns.values[0] = "true"
df2['predict'] = df2['predict'].astype(int)

In [3]:
concatenate = pd.concat([df1,df2, df3], axis=1)
concatenate

pt  predict  true
0       0.178055        2     2
1       0.499588        0     0
2      -0.199521        1     1
3      -2.179800        0     0
4      -0.196326        1     1
...          ...      ...   ...
198191 -0.196402        1     1
198192  0.198409        0     2
198193  0.198085        2     2
198194  0.168638        0     2
198195  0.171551        2     2

[198196 rows x 3 columns]

In [4]:
list1 = []
list2 = []

In [5]:
binValidate1 = concatenate.loc[(concatenate['pt'] < 0.1) & (concatenate['pt'] >= 0.0)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate1.predict == 0))/(binValidate1.shape[0]) )

binValidate2 = concatenate.loc[(concatenate['pt'] < 0.2) & (concatenate['pt'] >= 0.1)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate2.predict == 0))/(binValidate2.shape[0]) )

binValidate3 = concatenate.loc[(concatenate['pt'] < 0.3) & (concatenate['pt'] >= 0.2)]
list1.append( binValidate3.shape[0])
list2.append( sum((binValidate3.predict == 0))/(binValidate3.shape[0]) )

In [6]:
bin4 = concatenate.loc[  ((concatenate['pt'] < 0.4) & (concatenate['pt'] >= 0.3)  )       ]
list1.append(bin4.shape[0])
list2.append( sum((bin4.predict == 0))/(bin4.shape[0]))

In [7]:
bin5 = concatenate.loc[  ((concatenate['pt'] < 0.5) & (concatenate['pt'] >= 0.4)  )] 
list1.append(bin5.shape[0])
list2.append( sum((bin5.predict == 0))/(bin5.shape[0]))

In [8]:
#bin6 = concatenate.loc[  ((concatenate['pt'] < 0.6) & (concatenate['pt'] >= 0.5) ) | ( (concatenate['pt'] > -0.6) & (concatenate['pt'] <= -0.5)   )]
bin6 = concatenate.loc[(concatenate['pt'] < 0.6) & (concatenate['pt'] >= 0.5)]
list1.append(bin6.shape[0])
list2.append( sum((bin6.predict == 0))/(bin6.shape[0]) )

In [9]:
#bin7 = concatenate.loc[  ((concatenate['pt'] < 0.7) & (concatenate['pt'] >= 0.6) ) | ( (concatenate['pt'] > -0.7) & (concatenate['pt'] <= -0.6)   )] 
bin7 = concatenate.loc[(concatenate['pt'] < 0.7) & (concatenate['pt'] >= 0.6)]
list1.append(bin7.shape[0])
list2.append( sum((bin7.predict == 0))/(bin7.shape[0]) )

In [10]:
#bin8 = concatenate.loc[  ((concatenate['pt'] < 0.8) & (concatenate['pt'] >= 0.7) ) | ( (concatenate['pt'] > -0.8) & (concatenate['pt'] <= -0.7)    )]
bin8 = concatenate.loc[(concatenate['pt'] < 0.8) & (concatenate['pt'] >= 0.7)]
list1.append(bin8.shape[0])
list2.append( sum((bin8.predict == 0))/(bin8.shape[0]) )

In [11]:
#bin9 = concatenate.loc[  ((concatenate['pt'] < 0.9) & (concatenate['pt'] >= 0.8) ) | ( (concatenate['pt'] > -0.9) & (concatenate['pt'] <= -0.8)   )] 
bin9 = concatenate.loc[(concatenate['pt'] < 0.9) & (concatenate['pt'] >= 0.8)]
list1.append(bin9.shape[0])
list2.append( sum((bin9.predict == 0))/(bin9.shape[0]) )

In [12]:
#bin10 = concatenate.loc[  ((concatenate['pt'] < 1.0) & (concatenate['pt'] >= 0.9) ) | ( (concatenate['pt'] > -1.0) & (concatenate['pt'] <= -0.9)    )]
bin10 = concatenate.loc[(concatenate['pt'] < 1.0) & (concatenate['pt'] >= 0.9)]
list1.append(bin10.shape[0])
list2.append( sum((bin10.predict == 0))/(bin10.shape[0]) )

In [13]:
#bin11 = concatenate.loc[  ((concatenate['pt'] < 1.1) & (concatenate['pt'] >= 1.0) ) | ( (concatenate['pt'] > -1.1) & (concatenate['pt'] <= -1.0)    )]
bin11 = concatenate.loc[(concatenate['pt'] < 1.1) & (concatenate['pt'] >= 1.0)]
list1.append(bin11.shape[0])
list2.append( sum((bin11.predict == 0))/(bin11.shape[0]) )

In [14]:
#bin12 = concatenate.loc[  ((concatenate['pt'] < 1.2) & (concatenate['pt'] >= 1.1) ) | ( (concatenate['pt'] > -1.2) & (concatenate['pt'] <= -1.1)    )]
bin12 = concatenate.loc[(concatenate['pt'] < 1.2) & (concatenate['pt'] >= 1.1)]
list1.append(bin12.shape[0])
list2.append( sum((bin12.predict == 0))/(bin12.shape[0]) )

In [15]:
#bin13 = concatenate.loc[  ((concatenate['pt'] < 1.3) & (concatenate['pt'] >= 1.2) ) | ( (concatenate['pt'] > -1.3) & (concatenate['pt'] <= -1.2)    )]
bin13 = concatenate.loc[(concatenate['pt'] < 1.3) & (concatenate['pt'] >= 1.2)]
list1.append(bin13.shape[0])
list2.append( sum((bin13.predict == 0))/(bin13.shape[0]) )

In [16]:
#bin14 = concatenate.loc[  ((concatenate['pt'] < 1.4) & (concatenate['pt'] >= 1.3) ) | ( (concatenate['pt'] > -1.4) & (concatenate['pt'] <= -1.3)    )]
bin14 = concatenate.loc[(concatenate['pt'] < 1.4) & (concatenate['pt'] >= 1.3)]
list1.append(bin14.shape[0])
list2.append( sum((bin14.predict == 0))/(bin14.shape[0]) )

In [17]:
#bin15 = concatenate.loc[  ((concatenate['pt'] < 1.5) & (concatenate['pt'] >= 1.4) ) | ( (concatenate['pt'] > -1.5) & (concatenate['pt'] <= -1.4)   )] 
bin15 = concatenate.loc[(concatenate['pt'] < 1.5) & (concatenate['pt'] >= 1.4)]
list1.append(bin15.shape[0])
list2.append( sum((bin15.predict == 0))/(bin15.shape[0]) )

In [18]:
#bin16 = concatenate.loc[  ((concatenate['pt'] < 1.6) & (concatenate['pt'] >= 1.5) ) | ( (concatenate['pt'] > -1.6) & (concatenate['pt'] <= -1.5)   )] 
bin16 = concatenate.loc[(concatenate['pt'] < 1.6) & (concatenate['pt'] >= 1.5)]
list1.append(bin16.shape[0])
list2.append( sum((bin16.predict == 0))/(bin16.shape[0]) )

In [19]:
#bin17 = concatenate.loc[  ((concatenate['pt'] < 1.7) & (concatenate['pt'] >= 1.6) ) | ( (concatenate['pt'] > -1.7) & (concatenate['pt'] <= -1.6)    )]
bin17 = concatenate.loc[(concatenate['pt'] < 1.7) & (concatenate['pt'] >= 1.6)]
list1.append(bin17.shape[0])
list2.append( sum((bin17.predict == 0))/(bin17.shape[0]) )

In [20]:
#bin18 = concatenate.loc[  ((concatenate['pt'] < 1.8) & (concatenate['pt'] >= 1.7) ) | ( (concatenate['pt'] > -1.8) & (concatenate['pt'] <= -1.7)    )]
bin18 = concatenate.loc[(concatenate['pt'] < 1.8) & (concatenate['pt'] >= 1.7)]
list1.append(bin18.shape[0])
list2.append( sum((bin18.predict == 0))/(bin18.shape[0]) )

In [21]:
#bin19 = concatenate.loc[  ((concatenate['pt'] < 1.9) & (concatenate['pt'] >= 1.8) ) | ( (concatenate['pt'] > -1.9) & (concatenate['pt'] <= -1.8)   )] 
bin19 = concatenate.loc[(concatenate['pt'] < 1.9) & (concatenate['pt'] >= 1.8)]
list1.append(bin19.shape[0])
list2.append( sum((bin19.predict == 0))/(bin19.shape[0]) )

In [22]:
#bin20 = concatenate.loc[  ((concatenate['pt'] < 2.0) & (concatenate['pt'] >= 1.9) ) | ( (concatenate['pt'] > -2.0) & (concatenate['pt'] <= -1.9)    )]
bin20 = concatenate.loc[(concatenate['pt'] < 2.0) & (concatenate['pt'] >= 1.9)]
list1.append(bin20.shape[0])
list2.append( sum((bin20.predict == 0))/(bin20.shape[0]) )

In [23]:
#bin21 = concatenate.loc[  ((concatenate['pt'] < 2.1) & (concatenate['pt'] >= 2.0) ) | ( (concatenate['pt'] > -2.1) & (concatenate['pt'] <= -2.0)    )]
bin21 = concatenate.loc[(concatenate['pt'] < 2.1) & (concatenate['pt'] >= 2.0)]
list1.append(bin21.shape[0])
list2.append( sum((bin21.predict == 0))/(bin21.shape[0]) )

In [24]:
#bin22 = concatenate.loc[  ((concatenate['pt'] < 2.2) & (concatenate['pt'] >= 2.1) ) | ( (concatenate['pt'] > -2.2) & (concatenate['pt'] <= -2.1)    )]
bin22 = concatenate.loc[(concatenate['pt'] < 2.2) & (concatenate['pt'] >= 2.1)]
list1.append(bin22.shape[0])
list2.append( sum((bin22.predict == 0))/(bin22.shape[0]) )

In [25]:
#bin23 = concatenate.loc[  ((concatenate['pt'] < 2.3) & (concatenate['pt'] >= 2.2) ) | ( (concatenate['pt'] > -2.3) & (concatenate['pt'] <= -2.2)    )]
bin23 = concatenate.loc[(concatenate['pt'] < 2.3) & (concatenate['pt'] >= 2.2)]
list1.append(bin23.shape[0])
list2.append( sum((bin23.predict == 0))/(bin23.shape[0]) )

In [26]:
#bin24 = concatenate.loc[  ((concatenate['pt'] < 2.4) & (concatenate['pt'] >= 2.3) ) | ( (concatenate['pt'] > -2.4) & (concatenate['pt'] <= -2.3)    )]
bin24 = concatenate.loc[(concatenate['pt'] < 2.4) & (concatenate['pt'] >= 2.3)]
list1.append(bin24.shape[0])
list2.append( sum((bin24.predict == 0))/(bin24.shape[0]) )

In [27]:
#bin25 = concatenate.loc[  ((concatenate['pt'] < 2.5) & (concatenate['pt'] >= 2.4) ) | ( (concatenate['pt'] > -2.5) & (concatenate['pt'] <= -2.4)    )]
bin25 = concatenate.loc[(concatenate['pt'] < 2.5) & (concatenate['pt'] >= 2.4)]
list1.append(bin25.shape[0])
list2.append( sum((bin25.predict == 0))/(bin25.shape[0]) )

In [28]:
#bin26 = concatenate.loc[  ((concatenate['pt'] < 2.6) & (concatenate['pt'] >= 2.5) ) | ( (concatenate['pt'] > -2.6) & (concatenate['pt'] <= -2.5)    )]
bin26 = concatenate.loc[(concatenate['pt'] < 2.6) & (concatenate['pt'] >= 2.5)]
list1.append(bin26.shape[0])
list2.append( sum((bin26.predict == 0))/(bin26.shape[0]) )

In [29]:
#bin27 = concatenate.loc[  ((concatenate['pt'] < 2.7) & (concatenate['pt'] >= 2.6) ) | ( (concatenate['pt'] > -2.7) & (concatenate['pt'] <= -2.6)    )]
bin27 = concatenate.loc[(concatenate['pt'] < 2.7) & (concatenate['pt'] >= 2.6)]
list1.append(bin27.shape[0])
list2.append( sum((bin27.predict == 0))/(bin27.shape[0]) )

In [30]:
#bin28 = concatenate.loc[  ((concatenate['pt'] < 2.8) & (concatenate['pt'] >= 2.7) ) | ( (concatenate['pt'] > -2.8) & (concatenate['pt'] <= -2.7)    )]
bin28 = concatenate.loc[(concatenate['pt'] < 2.8) & (concatenate['pt'] >= 2.7)]
list1.append(bin28.shape[0])
list2.append( sum((bin28.predict == 0))/(bin28.shape[0]) )

In [31]:
#bin29 = concatenate.loc[  ((concatenate['pt'] < 2.9) & (concatenate['pt'] >= 2.8) ) | ( (concatenate['pt'] > -2.9) & (concatenate['pt'] <= -2.8)    )]
bin29 = concatenate.loc[(concatenate['pt'] < 2.9) & (concatenate['pt'] >= 2.8)]
list1.append(bin29.shape[0])
list2.append( sum((bin29.predict == 0))/(bin29.shape[0]) )

In [32]:
#bin30 = concatenate.loc[  ((concatenate['pt'] < 3.0) & (concatenate['pt'] >= 2.9) ) | ( (concatenate['pt'] > -3.0) & (concatenate['pt'] <= -2.9)    )]
bin30 = concatenate.loc[(concatenate['pt'] < 3.0) & (concatenate['pt'] >= 2.9)]
list1.append(bin30.shape[0])
list2.append( sum((bin30.predict == 0))/(bin30.shape[0]) )

In [33]:
bin31 = concatenate.loc[(concatenate['pt'] < 3.1) & (concatenate['pt'] >= 3.0)]
bin32 = concatenate.loc[(concatenate['pt'] < 3.2) & (concatenate['pt'] >= 3.1)]
bin33 = concatenate.loc[(concatenate['pt'] < 3.3) & (concatenate['pt'] >= 3.2)]
bin34 = concatenate.loc[(concatenate['pt'] < 3.4) & (concatenate['pt'] >= 3.3)]
bin35 = concatenate.loc[(concatenate['pt'] < 3.5) & (concatenate['pt'] >= 3.4)]
bin31_35 = bin31.shape[0] + bin32.shape[0]+ bin33.shape[0] + bin34.shape[0]+ bin35.shape[0]
list1.append(bin31_35)
list2.append((sum(bin31.predict == 0) +sum(bin32.predict == 0) + sum(bin33.predict == 0) + sum(bin34.predict == 0) + sum(bin35.predict == 0))/bin31_35 ) 

In [34]:
bin36 = concatenate.loc[(concatenate['pt'] < 3.6) & (concatenate['pt'] >= 3.5)]
bin37 = concatenate.loc[(concatenate['pt'] < 3.7) & (concatenate['pt'] >= 3.6)]
bin38 = concatenate.loc[(concatenate['pt'] < 3.8) & (concatenate['pt'] >= 3.7)]
bin39 = concatenate.loc[(concatenate['pt'] < 3.9) & (concatenate['pt'] >= 3.8)]
bin40 = concatenate.loc[(concatenate['pt'] < 4.0) & (concatenate['pt'] >= 3.9)]
bin36_40 = bin36.shape[0] + bin37.shape[0]+ bin38.shape[0] + bin39.shape[0]+ bin40.shape[0]
list1.append(bin36_40)
list2.append((sum(bin36.predict == 0) +sum(bin37.predict == 0) + sum(bin38.predict == 0) + sum(bin39.predict == 0) + sum(bin40.predict == 0))/bin36_40 ) 

In [35]:
bin41 = concatenate.loc[(concatenate['pt'] < 4.1) & (concatenate['pt'] >= 4.0)]
bin42 = concatenate.loc[(concatenate['pt'] < 4.2) & (concatenate['pt'] >= 4.1)]
bin43 = concatenate.loc[(concatenate['pt'] < 4.3) & (concatenate['pt'] >= 4.2)]
bin44 = concatenate.loc[(concatenate['pt'] < 4.4) & (concatenate['pt'] >= 4.3)]
bin45 = concatenate.loc[(concatenate['pt'] < 4.5) & (concatenate['pt'] >= 4.4)]
bin41_45 = bin41.shape[0] + bin42.shape[0]+ bin43.shape[0] + bin44.shape[0]+ bin45.shape[0] 
list1.append(bin41_45)
list2.append((sum(bin41.predict == 0) +sum(bin42.predict == 0) + sum(bin43.predict == 0) + sum(bin44.predict == 0) + sum(bin45.predict == 0))/bin41_45 ) 

In [36]:
bin46 = concatenate.loc[(concatenate['pt'] < 4.6) & (concatenate['pt'] >= 4.5)]
bin47 = concatenate.loc[(concatenate['pt'] < 4.7) & (concatenate['pt'] >= 4.6)]
bin48 = concatenate.loc[(concatenate['pt'] < 4.8) & (concatenate['pt'] >= 4.7)]
bin49 = concatenate.loc[(concatenate['pt'] < 4.9) & (concatenate['pt'] >= 4.8)]
bin50 = concatenate.loc[(concatenate['pt'] < 5.0) & (concatenate['pt'] >= 4.9)]
bin46_50 = bin46.shape[0] + bin47.shape[0]+ bin48.shape[0] + bin49.shape[0]+ bin50.shape[0]  
list1.append(bin46_50)
list2.append((sum(bin46.predict == 0) +sum(bin47.predict == 0) + sum(bin48.predict == 0) + sum(bin49.predict == 0) + sum(bin50.predict == 0))/bin46_50 ) 

In [37]:
len(list2)

34

In [38]:
y_values=np.array([list2])
y_values

array([[0.03603604, 0.21505724, 0.46501014, 0.66322678, 0.7742915 ,
        0.82888661, 0.85035569, 0.86977824, 0.87583376, 0.88117589,
        0.89335828, 0.89230156, 0.89602446, 0.9085044 , 0.90450726,
        0.90869183, 0.9005291 , 0.91327913, 0.91366906, 0.92227979,
        0.90413943, 0.92307692, 0.91916168, 0.90298507, 0.91699605,
        0.94618834, 0.91860465, 0.92567568, 0.9352518 , 0.94354839,
        0.89918256, 0.93478261, 0.88349515, 0.91666667]])

In [39]:
x_values=np.array([list1])
x_values

array([[ 111,  111, 3944, 3973, 3952, 3898, 3936, 3878, 3898, 4048, 3207,
        2507, 1962, 1705, 1309, 1139,  945,  738,  695,  579,  459,  390,
         334,  268,  253,  223,  172,  148,  139,  124,  367,  184,  103,
          72]])

In [40]:
first = y_values*(1-y_values)
second = first/x_values
errors = np.sqrt(second)
errors

array([[0.01769039, 0.0389973 , 0.0079421 , 0.00749792, 0.00664994,
        0.0060321 , 0.00568595, 0.00540433, 0.00528192, 0.00508585,
        0.00545038, 0.00619132, 0.0068909 , 0.00698235, 0.00812309,
        0.00853496, 0.00973601, 0.01035942, 0.01065333, 0.01112651,
        0.01374141, 0.0134932 , 0.01491528, 0.01807974, 0.01734494,
        0.01511035, 0.0208497 , 0.02156076, 0.02087232, 0.02072571,
        0.0157166 , 0.01820238, 0.03161226, 0.03257233]])

In [41]:
np.savetxt('PositiveYValues.out',y_values, delimiter=',')
np.savetxt('errorsPositive.out', errors, delimiter=',')