In [1]:
import numpy as np
import pandas as pd
from pandas import read_csv
import math
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('/home/jieun201/aug20_make3Classes_dataset/trainTestSamples/test/shuffledTest.csv')
df1

y-local        pt    0    1    2    3    4    5    6    7  ...  264  \
0      -5.906050  0.178055  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
1       8.082580  0.499588  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
2       0.127132 -0.199521  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
3      -6.684330 -2.179800  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
4      -2.855120 -0.196326  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
...          ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
198191  4.484750 -0.196402  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
198192  0.515319  0.198409  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
198193  2.604940  0.198085  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
198194  7.879390  0.168638  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
198195  6.782440  0.171551  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   

        265  266  267  268  269  270  271  272  ptLabel  
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        2  
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        0  
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        1  
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        0  
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        1  
...     ...  ...  ...  ...  ...  ...  ...  ...      ...  
198191  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        1  
198192  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        2  
198193  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        2  
198194  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        2  
198195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0        2  

[198196 rows x 276 columns]

In [3]:
df1['y-local'].to_csv('y-localTest.csv',index=False)

In [4]:
#these are the labels for the training set
df1['ptLabel'].to_csv('labelsTest.csv',index=False)

In [5]:
df1.drop('y-local', axis=1, inplace=True)
df1.drop('pt', axis=1, inplace=True)
df1.drop('ptLabel', axis=1, inplace=True)
df1

0    1    2    3    4    5    6    7    8    9  ...  263  264  265  \
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
198191  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198192  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198193  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198194  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        266  267  268  269  270  271  272  
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  
198191  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198192  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198193  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198194  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[198196 rows x 273 columns]

In [14]:
import numpy as np
df2NP = np.array(df1)

In [15]:
df2NP[(df2NP < 400)] = 0
df2NP[(df2NP >= 400) & (df2NP < 1600)] = 1
df2NP[(df2NP >= 1600) & (df2NP < 2400)] = 2
df2NP[(df2NP >= 2400)] = 3

In [17]:
df2NP
backToPandas = pd.DataFrame(df2NP)
backToPandas

0    1    2    3    4    5    6    7    8    9    ...  263  264  265  \
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
198191  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198192  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198193  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198194  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
198195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        266  267  268  269  270  271  272  
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  
198191  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198192  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198193  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198194  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
198195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[198196 rows x 273 columns]

In [18]:
def sumRow(X):
    sum1 = 0
    sumList = []
    for i in X:
        sum1 = np.sum(i,axis=0)
        sumList.append(sum1)
        b = np.array(sumList)
    return b

list1 = []
for index, row in backToPandas.iterrows(): 
#for index, row in df1.iterrows():   
    rowSum = 0.0
    X = row.values
    X = np.reshape(X,(13,21))
    rowSum = sumRow(X)
    list1.append(rowSum)
#list1

[array([0., 0., 4., 5., 5., 7., 4., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 4., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 3., 5., 3., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 1., 3., 3., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 6., 9., 7., 0., 0., 0., 0., 0.]),
 array([ 0.,  0.,  0.,  0.,  0.,  7., 19., 10.,  0.,  0.,  0.,  0.,  0.]),
 array([0., 0., 4., 9., 9., 9., 2., 0., 0., 0., 0., 0., 0.]),
 array([ 3.,  3.,  4., 11.,  8.,  6.,  5.,  3.,  0.,  0.,  0.,  0.,  0.]),
 array([0., 0., 0., 0., 0., 7., 8., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 5., 5., 6., 6., 4., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 8., 8., 8., 7., 4., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 3., 2., 3., 0., 0., 0., 0., 0., 0.]),
 array([ 0.,  0.,  0.,  2.,  2., 48.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 array([0., 0., 1., 2., 1., 3., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 6., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 3., 2., 2.,

In [19]:
df_ySize = pd.DataFrame(list1)
df_sum = pd.DataFrame(list1)
df_ySize.to_csv('yProfileTest.csv',index=False)

In [20]:
dfA = pd.read_csv('yProfileTest.csv')
dfA

0    1    2    3    4    5    6    7    8    9   10   11   12
0       0.0  0.0  4.0  5.0  5.0  7.0  4.0  1.0  0.0  0.0  0.0  0.0  0.0
1       0.0  0.0  0.0  0.0  0.0  1.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0
2       0.0  0.0  0.0  0.0  3.0  5.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0
3       0.0  0.0  1.0  1.0  3.0  3.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4       0.0  0.0  0.0  0.0  0.0  6.0  9.0  7.0  0.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
198191  0.0  0.0  0.0  0.0  0.0  0.0  6.0  0.0  0.0  0.0  0.0  0.0  0.0
198192  0.0  0.0  0.0  0.0  2.0  3.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0
198193  0.0  0.0  0.0  0.0  1.0  8.0  7.0  5.0  0.0  0.0  0.0  0.0  0.0
198194  0.0  0.0  0.0  0.0  1.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
198195  0.0  0.0  0.0  1.0  3.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[198196 rows x 13 columns]

In [21]:
dfB = pd.read_csv('y-localTest.csv',usecols = ['y-local'])
dfB

y-local
0      -5.906050
1       8.082580
2       0.127132
3      -6.684330
4      -2.855120
...          ...
198191  4.484750
198192  0.515319
198193  2.604940
198194  7.879390
198195  6.782440

[198196 rows x 1 columns]

In [22]:
#now concatenate both dataframes since input will be: ysize and y_local
dfE = pd.concat([dfA,dfB],axis=1)
#dfE.to_csv('all.csv',index=False)
dfE

0    1    2    3    4    5    6    7    8    9   10   11   12  \
0       0.0  0.0  4.0  5.0  5.0  7.0  4.0  1.0  0.0  0.0  0.0  0.0  0.0   
1       0.0  0.0  0.0  0.0  0.0  1.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0   
2       0.0  0.0  0.0  0.0  3.0  5.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   
3       0.0  0.0  1.0  1.0  3.0  3.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  6.0  9.0  7.0  0.0  0.0  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
198191  0.0  0.0  0.0  0.0  0.0  0.0  6.0  0.0  0.0  0.0  0.0  0.0  0.0   
198192  0.0  0.0  0.0  0.0  2.0  3.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   
198193  0.0  0.0  0.0  0.0  1.0  8.0  7.0  5.0  0.0  0.0  0.0  0.0  0.0   
198194  0.0  0.0  0.0  0.0  1.0  7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
198195  0.0  0.0  0.0  1.0  3.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

         y-local  
0      -5.906050  
1       8.082580  
2       0.127132  
3      -6.684330  
4      -2.855120  
...          ...  
198191  4.484750  
198192  0.515319  
198193  2.604940  
198194  7.879390  
198195  6.782440  

[198196 rows x 14 columns]

In [23]:
dfE.to_csv('InputTestSet.csv',index=False)